version: "3"

services:
  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - /tmp/dockerdir:/etc/mysql/conf.d/
    ports:
      - 4306:3306

  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./backend:/myapp
      - bundle:/myapp/vendor/bundle
    environment:
      RAILS_ENV: development
    ports:
      - 3001:3000
    depends_on:
      - db

  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "cd app && yarn && yarn start"
    ports:
      - "4000:3000"

volumes:
  mysql_data:
  bundle: